spring:
  datasource:
    db1:
      name: db1
      initial-size: 1
      max-active: 50
      validation-query: select 1 from DUAL
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3309/team_task?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
      username: root
      password: 1234
    db2:
      name: db2
      initial-size: 1
      max-active: 50
      validation-query: select 2 from DUAL
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/team_task?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
      username: root
      password: 1234

management.health.mail.enabled: false

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#logging:
#  level:
#    org.apache.ibatis: debug
#    org.mybatis: debug
#    com.bright: debug
