spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3309/quartz_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  jackson:
    time-zone: Asia/Shanghai
  quartz:
    #auto-startup: false
    startup-delay: 5s
    job-store-type: jdbc
    #jdbc.initialize-schema: always
    properties:
      org.quartz.jobStore.isClustered: true
      org.quartz.scheduler.instanceId: AUTO
      #org.quartz.scheduler.instanceName: AUTO
      org.quartz.threadPool.threadCount: 5
